# Generated by Django 4.2.2 on 2023-06-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('client_id', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
            ],
        ),
    ]
