# Generated by Django 4.2.2 on 2023-06-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contamercado',
            name='conta_pai_ou_filha',
            field=models.BooleanField(default=False, verbose_name='Tipo conta'),
        ),
    ]
