# Generated by Django 4.2.2 on 2023-06-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_contamercado_conta_pai_ou_filha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contamercado',
            name='conta_pai_ou_filha',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Tipo conta'),
        ),
    ]
