# Generated by Django 4.2.2 on 2023-06-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_contamercado_conta_pai_ou_filha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contamercado',
            name='status_account',
        ),
        migrations.AddField(
            model_name='contamercado',
            name='access_token_ativo',
            field=models.BooleanField(default=True, verbose_name='Access Token ativa'),
        ),
        migrations.AddField(
            model_name='contamercado',
            name='conta_utilizada',
            field=models.BooleanField(default=True, verbose_name='Conta Utilizada'),
        ),
    ]
