# Generated by Django 4.2.2 on 2023-06-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_contamercado_status_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contamercado',
            name='conta_utilizada',
            field=models.BooleanField(blank=True, default=True, verbose_name='Conta Utilizada'),
        ),
    ]
