# Generated by Django 4.2.2 on 2023-06-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_contamercado_access_token_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contamercado',
            name='conta_ativa',
            field=models.BooleanField(default=True, verbose_name='Conta ativa'),
        ),
        migrations.AlterField(
            model_name='contamercado',
            name='status_account',
            field=models.BooleanField(default=True, verbose_name='Access Token ativa'),
        ),
    ]
