# Generated by Django 4.2.2 on 2023-06-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_contamercado_conta_ativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contamercado',
            name='conta_ativa',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Conta ativa'),
        ),
    ]
