# Generated by Django 4.2.2 on 2023-06-24 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_contamercado_conta_ativa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContaMercado',
        ),
    ]
