# Generated by Django 4.2.2 on 2023-06-24 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('id_conta', models.IntegerField()),
                ('nome_conta', models.CharField(max_length=255, verbose_name='Nome da conta')),
                ('time_generate_access', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Geração Access Token')),
                ('status_account', models.BooleanField(default=True, verbose_name='Access Token ativa')),
                ('conta_ativa', models.BooleanField(blank=True, default=True, null=True, verbose_name='Conta ativa')),
                ('conta_pai_ou_filha', models.BooleanField(blank=True, default=False, null=True, verbose_name='Tipo conta')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dono')),
            ],
        ),
    ]
