# Generated by Django 4.2.2 on 2023-06-25 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contasml', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contamercado',
            name='refresh_token',
        ),
        migrations.AlterField(
            model_name='contamercado',
            name='time_generate_access',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Geração Access Token'),
        ),
    ]
