# Generated by Django 4.2.3 on 2023-07-09 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contasml', '0002_remove_contamercado_refresh_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('client_id', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='contamercado',
            name='refresh_token',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contamercado',
            name='time_generate_access',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Geração Access Token'),
        ),
    ]
